MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  WEIGHTS: "/apdcephfs/private_peixianchen/detection/Detic-30/models/model_final.pth"
  WITH_CAPTION: True
  SYNC_CAPTION_BATCH: True
  RESNETS:
    DEPTH: 50
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_BOX_HEAD:
    WS_NUM_PROPS: 1
    ADD_IMAGE_BOX: True
    NEG_CAP_WEIGHT: 1.0
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_v2_clip_a+cname_48.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
  ROI_HEADS:
    NUM_CLASSES: 48
    NAME: "CustomRes5ROIHeads"
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (25000, 35000)
  MAX_ITER: 45000
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder", "coco_caption_train_tags")
  TEST: ("coco_generalized_zeroshot_val",)
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (800, 800)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [4, 16]
  USE_RFS: [False, False]
  DATASET_MIN_SIZES: [[800, 800], [400, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'caption']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True
VERSION: 2
FP16: True
TEST:
  EVAL_PERIOD: 5000
# OUTPUT_DIR: output/Detic-COCO/detic_maxcaption
